import HomePage from './Home_Page'
import LoginPage from './Login_Page'
import RegisterPage from './Register_Page'
import Header from './Component/Header'
import HeaderAdmin from './Component/HeaderAdmin'
import Dashboard_Page from './Dashboard_Page'
import Banner from './Component/Banner'
import AddStudentPage from './AddStudent_Page'
import ViewStudentPage from './ViewStudent_Page'
import EditStudentPage from './EditStudentPage'
export{HomePage,LoginPage,RegisterPage,Header,HeaderAdmin,Dashboard_Page,Banner,AddStudentPage,ViewStudentPage,EditStudentPage}